baseurl = "/"
languageCode = "en-us"
title = "Improper Prior"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "©"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "Friends On The Internet"
    url = "/friends/"
    weight = 1
    
[[menu.main]]
    name = "Book Log"
    url = "/book_log/"
    weight = 2
    

[params]
    description = "Ben Ewing's blog."
    footer = "[Github](https://github.com/ben-e) | [LinkedIn](https://www.linkedin.com/in/ben-e/) | Built with Hugo 🧙"
    custom_css = ["css/theme-override.css"]
