---
author: Ben Ewing
title: Book Log
---

This is some of the media I've interacted with, by year.

## 2021

### Books

* _Dune_ - [In Progress]
* _The Return of the King_ - [In Progress]
* _Murder on the Orient Express_, Agatha Christie - I do enjoy Christie's books, and this is no exception. Not sure how I feel about the ending.

### Games

* _Fallout: New Vegas_ - [In Progress]
* _Spiritfarer_ - [In Progress]

### Movies

* _Onward_ - I liked this movie. Not the best from Pixar, but pretty fun nontheless.

## 2020 (Incomplete)

### Books

* _Gideon the Ninth_, Tamsyn Muir - Took me quite a while to get into this book. I really did not like Gideon at first, but the world building really pulled me in. 
* _Harrow the Ninth_, Tamsyn Muir - I really liked this book, though I'd rather not read a book in the second person again (I do think this pays off for Muir, ultimately).
* _The Fellowship of the Ring_, J.R.R. Tolkien - Really enjoyed this more than I thought I would. Tolkien's characters can feel a little odd at times, and some passages can feel like  a slog to get through, but despite this Tolkien does a great job building tension and (of course) builds a really compelling world.
* _The Two Towers_, J.R.R. Tolkien - Most of the same notes from _Fellowship_ apply here, but I think I enjoyed the plot of _Towers_ more. I honestly appreciate that Tolkien's battle scenes are actually quite brief (unlike say, the movies).
* _The 7 1/2 Deaths of Evelyn Hardcastle_, Stuart Turton - This is a well written murder mystery with a fun premise, but it's ultimately a bit of a let down.
* _Woken Furies_, Richard K. Morgan - (Disclaimer: Morgan is not a great person.) Definitely a guilty pleasure book for me, as with the other _Altered Carbon_ books. I did enjoy it though.
* _Ancillary Justice_, Anne Leckie - I don't why, but I had a hard time getting through this book. At the end of the day, I did really enjoy it though. Very cool premise: a ship's AI downloads itself into one of the bodies it controls to escape a purge, and seeks revenge.
* _Sleeping Giants_, Sylvain Neuvel - Not really worth reading.
* _The Last Wish_, Andrzej Sapkowski - I really enjoyed this book, especially after watching the Netflix series. It take the form of a series of intertwined short stories that collectively do a great job of building an interesting world and characters I already feel attached to.

### Games

* _The Outer Wilds_ - I really loved this game. It's premised on the idea that if the world it creates is interesting, the curious will want to explore it. It succeeds wonderfully at this. I found the ending quite touching as well.

### Movies

* _Knives Out_ - As good as everyone said it was.

