---
title: Data Science Interview Questions
author: Ben Ewing
slug: data-science-interview-questions
categories:
  - technical
tags: []
---

## Introduction

I've seen a number of articles/posts pop up around the internet with lists of data science interview questions. I thought it might be a good exercise in communication and data science knowledge to answer these questions. I am finding it harder than I would have expected to write good (and hopefully useful) answers!

Question sources:

* [HackerNoon - 160+ Data Science Interview Questions](https://hackernoon.com/160-data-science-interview-questions-415s3y2a)

Additional resources:

* [Alexey Grigorev](http://alexeygrigorev.com/) has put together a whole GitHub repo with data science interview questions _and_ answers, [available here](https://github.com/alexeygrigorev/data-science-interviews/). He also has his own extensive collection of [resources](https://github.com/alexeygrigorev/data-science-interviews/blob/master/awesome.md).
* [Chris Albon](https://chrisalbon.com/) has a collection of machine learning flashcards, [available as a whole set for a price](https://machinelearningflashcards.com/), or sporadically posted [on his Twitter feed](https://twitter.com/chrisalbon). I've found these to be a useful way to identify gaps in my knowledge.

## Supervised machine learning

### What is supervised machine learning?

Supervised machine learning is when we use a dataset, $X$, to predict some known target value $y$ where $y$ might be a label/class or some continuous value. In unsupervised learning we learn about a dataset $X$ without any label, for example clustering individuals.

## Linear Regression

### What is regression? Which models can you use to solve a regression problem?

In a regression problem we predict a continuous value (rather than a label). Linear regression is very common; it can be augmented with polynomial features or regularization terms (lasso and ridge regression). Many other algorithms can also be used for regression problems, such as random forests with regression trees.

### What is linear regression? When do we use it?

For data $X$, observation $i$, a linear regression predicts a value $y_i = x_i^T\beta$ for a set of coefficients $\beta$. We typically assume there to be some error term $\epsilon_i$ that is normally distributed around 0. 

Additional notes:

* We can add an extra column of 1s to the data to include an intercept term. The column of 1s allows us to add an extra $\beta_0$ which (in the case of linear regression with a single variable) changes where on the y-axis the line passes through. Without this term the line will just pass through 0.

* The 'linear' in linear regression refers to the relationship between $y$ and $\beta$, the $x_i$'s can be polynomials, as in the case of polynomial regression.

* While the $\beta$'s can be found through a number of techniques, choosing $\beta$ to minimize $(y- X\beta)^T(y- X\beta)$ (as is very common, this is just ordinary least squares) gives a very elegant closed form: $\hat{\beta} = (X^TX)^{-1}X^Ty$.

## What’s the normal distribution? Why do we care about it? 

The normal distribution with with parameters $\mu$ and $\sigma^2$ as $p(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp{\left(-\frac{1}{2\sigma^2}(x-\mu)^2\right)}$.

There are a lot of reasons to care about the normal distribution (e.g. Alexey talks about the central limit theorem for this question). Perhaps the reason the normal distribution pops up everywhere is that it's kernel (with known variance) is just the squared difference between two quantities, which we use quite often.

## How do we check if a variable follows the normal distribution?

For exploratory data analysis (EDA) I would just plot a histogram or the empirical density. For a more formal setting one could look at the skew and kurtosis (both 0 for a normal distribution), or run any one of the many [normality tests](https://en.wikipedia.org/wiki/Normality_test).

This is a pretty common procedure when looking at regression residuals, remember we want a normal error!

## What if we want to build a model for predicting prices? Are prices distributed normally? Do we need to do any pre-processing for prices?

My best guess (i.e. based on only my priors, no data) is that prices are not normally distributed, in fact I would expect the distribution of prices to be very skewed due to the presence of high-end luxury goods. We can deal with this by using a log-transformation on the data. I assume this question is not asking about pre-processing like converting to the same currency or other data cleaning steps.

## What are the methods for solving linear regression do you know?

See my answer for "What is linear regression? When do we use it?"