---
author: Ben Ewing
title: Things I Like
---

These are some things I like:

## Blogs

* [Gordon Shotwell's Data Science Blog](https://blog.shotwell.ca/) - I stumbled on Gordon's blog because of a [HackerNews](https://news.ycombinator.com/item?id=21965248) post. I have so far found all of his posts to be very insightful and well thought out.
* [Eric's Movie Blog](https://dweemeister.tumblr.com/) - This is a movie blog run by a friend from undergraduate. His movie reviews are extremely well written.
* [Craig Gidney's Algorithmic Assertions](https://algassert.com/) - This is a fantastic math/computer science blog.
* [Kristoffer Magnusson's R Psychologist](https://rpsychologist.com/) - Kristoffer's blog is full of seriously beautiful interactive visualizations and intuitive explanations of many topics across statistics. Kristoffer is also the creator of the [powerlmm](https://cran.r-project.org/web/packages/powerlmm/index.html) package for power analysis.
* [The Littlest Dick](https://thelittlestdick.wordpress.com/) - This is a blog written by an acquaintance of mine who wishes to remain _unsearchable_.

## People

* [Neha Gupta](https://guptane6.github.io/index.html) - Neha is in my M.S. Economics and Computation cohort at Duke. She's interested in topics around privacy and computational economics.
* [Haoming Li](https://haoming.li/) - Haoming is in my M.S. Economics and Computation cohort at Duke. His research on preference elicitation is very interesting.

## Artists

* [Matt Tarpley's Cat's Cafe](https://www.catscafecomics.com/) - Matt writes/illustrates very wholesome comics. [Current favorite](https://www.catscafecomics.com/post/613750137827770368/i-am-trying).
* [Maria Protopopov's Mo(ve)ments](https://mariaprotopopov.com/) - Maria is a friend from UC Santa Cruz who uses photography as a medium for meditation and reflection.
* [Aura Walmer's Art + Music](https://aurawalmer.com/) - Aura (another friend from UC Santa Cruz!) is a wonderfully talented artist across several mediums. I've got one print of her's in my house right now, and I hope to add more in the future!

## Books

* [Osvaldo Martin's Bayesian Analysis with Python](https://www.packtpub.com/big-data-and-business-intelligence/bayesian-analysis-python-second-edition) - Review forthcoming, but so far I really like this book!